"""empty message

Revision ID: 373a8fc901b6
Revises: 
Create Date: 2020-09-09 17:26:01.066324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373a8fc901b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
